#spring:
#  elasticsearch:
#    uris: https://10.25.241.35:9200
#    # 内置超级用户
#    username: elastic
#    # 启动时控制台给出的初始密码
#    password: elastic
#    socket-timeout: 30s
#    connection-timeout: 5s
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      auto-index-creation: true   # 开发阶段让框架自动建索引
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
  elasticsearch:
    rest:
#      uris: https://10.25.241.35:9200
      uris: https://es01:9200
      username: elastic
      password: elastic
      socket-timeout: 30s
      connection-timeout: 5s
  data:
    elasticsearch:
      enabled: false
      repositories:
        enabled: false
      auto-index-creation: true